# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [28]:
zero_matrix = np.zeros(10)
zero_matrix

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [27]:
ones_matrix = np.ones(10)
ones_matrix

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [41]:
array_of_five = np.array([5 for i in range(10)])
array_of_five

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [47]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [54]:
eye_matrix_five = np.eye(10)*5
eye_matrix_five.diagonal()

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [60]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [66]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

##find the memory size of any array

In [76]:
print("the size of eye_matrix_five array is: ",format(eye_matrix_five.size))
print("the memory size of eye_matrix_five array is: ",format(eye_matrix_five.size* eye_matrix_five.itemsize))

the size of eye_matrix_five array is:  100
the memory size of eye_matrix_five array is:  800


#### Create a 3x3 matrix with values ranging from 0 to 8

In [81]:
print(np.arange(9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [84]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [96]:
np.random.random(10)

array([0.28475633, 0.24706345, 0.04562613, 0.88895875, 0.83561729,
       0.66116817, 0.08750077, 0.84806637, 0.79376108, 0.45435551])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [107]:
np.random.normal(size=25)

array([-1.4513851 , -1.8695724 , -0.65397375,  1.7066925 , -0.86582492,
        1.02312052, -0.85575731, -0.4693018 ,  0.26858645,  0.44899077,
        0.85117782, -0.76667351,  1.02499552,  0.80983838,  0.53849697,
       -1.02498209, -1.0750923 , -0.16611157,  0.14119692,  1.5546939 ,
        0.07269821, -0.7900085 , -0.22640503, -0.40412558,  0.20396722])

#### Create the following matrix:

#### Create an array of 20 linearly spaced points between 0 and 1:

In [109]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [111]:
a = np.array(0.12076381)
a

array(0.12076381)

In [252]:
radnom = np.random.normal( -0.15117509080000002, 0.7415546805496589, size= 25)
radnom

array([-0.21116434, -1.0192282 , -0.424326  ,  0.81921602,  0.88473509,
       -0.81718542, -0.41064697,  0.89483608, -0.17978773,  0.14739748,
       -1.23679673, -1.25229557, -0.49971901, -1.8520452 , -0.88524559,
        0.21399675, -0.301218  ,  0.50932603,  0.21950723,  0.17222548,
        0.20934928, -0.13636407,  0.12229232,  1.24907624, -1.56801498])

In [117]:
c = np.arange(100)*0.01
c

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99])

In [125]:
d = np.arange(1,26).reshape(5,5)
d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [123]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [221]:
d[2:5, [1,2,3,4]]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [222]:
d[3,4]

20

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [228]:
d[0:3, [1]]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [230]:
d[4]

array([21, 22, 23, 24, 25])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [232]:
d[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

####Create a 10*10  matrix with 1 on the border and 0 inside

In [178]:
zeros_ones = np.zeros(100).reshape(10,10)

zeros_ones[0], zeros_ones[9] =1 ,1 

for rows in range(1,9):
    zeros_ones[rows][0],  zeros_ones[rows][9]=1, 1

print("a 10*10 matrix with 1 on the border and 0 inside: ")
print(zeros_ones)

a 10*10 matrix with 1 on the border and 0 inside: 
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### Now do the following

#### find common values between two arrays

In [132]:
x1 = np.array([0, 2, 2, 2, 4, 5, 1, 4, 8, 5])
x2 = np.array([2, 2, 3, 4, 7, 4, 6, 9, 4, 8])


In [143]:
np.intersect1d(x1, x2)

array([2, 4, 8])

####You can use flatten to flatten your array into a 1D array

In [135]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [136]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

#### Get the sum of all the values in mat

In [138]:
mat = d
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [139]:
mat.sum()

325

#### Get the standard deviation of the values in mat

In [140]:
mat.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [141]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

# Great Job!